site_name: Sheffield Mencap 
site_email: info@sheffieldmencap.org.uk
admin_email: developmentmanager@sheffieldmencap.org.uk
site_url: http://sheffieldmencap.org
live_site_url: http://sheffieldmencap.org
